version: "3"

services:
  web:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - .:/usr/src/app
    env_file:
      - config/docker.env
    depends_on:
      - database
    stdin_open: true
    tty: true

  database:
    image: postgres:12.5
    env_file:
      - config/docker.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  db_data:
