require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Lint/ScriptPermission:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec:
  Enabled: false

RSpec/FactoryBot:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
