version: '3.6'

services:
  app: &app_base
    image: ${DOCKER_IMAGE}
    environment:
      ENSURE_DEPENDENCIES: 1
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgres://postgres:password@pg:5432/inkind_admin_dev

  pg:
    volumes:
      - ./db/dbinit:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: password
