name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_GITHUB_CREDENTIALS }}'
          enable-AzPSSession: true
      -
        name: Docker build and push
        run: |
          az acr login --name inkindadmin
          docker build . -t inkindadmin.azurecr.io/inkindadmin:{{ github.ref }}
          docker push inkindadmin.azurecr.io/inkindadmin:{{ github.ref }}

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_GITHUB_CREDENTIALS }}'
          enable-AzPSSession: true
      -
        name: Docker build and push
        run: |
          az acr login --name inkindadmin
          docker pull inkindadmin.azurecr.io/inkindadmin:{{ github.ref }}
          docker run --rm inkindadmin.azurecr.io/inkindadmin:{{ github.ref }} standardrb --format github

